openapi: 3.0.3

info:
  title: Inperium Server Talk Number Porting API
  description: |
    The initial version of Inperium Talk Number Porting API.
  version: 1.0.0-SNAPSHOT

servers:
  - url: http://api.inperium.com/v1/talkNumberPorting
  - url: https://api.inperium.com/v1/talkNumberPorting

security:
  - BearerAuth: [ ]
  - ApiKeyAuth: [ ]

paths:
  /health:
    get:
      tags:
        - Health Checks
      summary: Checks the health of the microservice
      operationId: checkHealth
      responses:
        200:
          description: An empty response that is used for OK non-returning operations
          content: { }
        default:
          description: Bad request, security violation, or internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'

  /portOrders:
    post:
      tags:
        - Port Orders
      summary: Create a new port order
      operationId: createPortOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PortOrderRequest'
      responses:
        201:
          description: A new port order has been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PortOrder'
        default:
          description: Bad request, security violation, or internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'

  /portOrders/{id}:
    patch:
      tags:
        - Port Orders
      summary: Partially update a port order
      operationId: partiallyUpdatePortOrder
      parameters:
        - $ref: '#/components/parameters/ResourceId'
      requestBody:
        description: Partially updates port order
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PortOrderRequest'
      responses:
        200:
          description: The port order has been modified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PortOrder'
        default:
          description: Bad request, security violation, or internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
    delete:
      tags:
        - Port Orders
      summary: Delete a port order
      operationId: deletePortOrder
      parameters:
        - $ref: '#/components/parameters/ResourceId'
      responses:
        204:
          description: The port order has been deleted
          content: { }
        default:
          description: Bad request, security violation, or internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'

components:

  securitySchemes:

    BearerAuth:
      type: http
      scheme: bearer

    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY

  parameters:

    ResourceId:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
    QueryPageNumber:
      name: pageNumber
      in: query
      description: Query parameter for the "pageNumber"
      schema:
        type: integer
        format: int64
    QueryPageSize:
      name: pageSize
      in: query
      description: Query parameter for the "pageSize"
      schema:
        type: integer
        format: int64
    QuerySort:
      name: sort
      in: query
      description: Query parameter for the "sort" criteria
      schema:
        type: string

  schemas:

    ResponseError:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorModel'

    ErrorModel:
      required:
        - code
        - type
      type: object
      properties:
        code:
          type: string
          description: HTTP error code returned by Inperium.
        message:
          type: string
          description: The message with event details.
        type:
          type: string
          description: The error level.
          enum:
            - ERROR
            - WARN
            - INFO
        details:
          type: string
          description: Comma-separated list of fields, which caused the error condition
      description: Each error contains information that might be helpful for troubleshooting issues.

    Id:
      type: string
      format: uuid

    Address:
      type: object
      required:
        - address
        - city
        - state
        - zip
      properties:
        address:
          type: string
        city:
          type: string
        state:
          type: string
        zip:
          type: string

    PortOrderRequest:
      type: object
      required:
        - talkId
        - address
        - phoneNumbers
        - letterOfAuthorization
        - billingStatements
        - tenantId
        - accountSid
      properties:
        talkId:
          $ref: '#/components/schemas/Id'
        firstName:
          type: string
        lastName:
          type: string
        companyName:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        phoneNumbers:
          type: array
          items:
            type: string
        letterOfAuthorization:
          $ref: '#/components/schemas/Id'
        billingStatements:
          type: array
          items:
            $ref: '#/components/schemas/Id'
        comment:
          type: string
        tenantId:
          $ref: '#/components/schemas/Id'
        accountSid:
          type: string

    PortOrder:
      type: object
      required:
        - id
      properties:
        id:
          $ref: '#/components/schemas/Id'
