# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ development ]

env:
  REPO_NAME: inperium-openapi

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Init
        run: |
          git config --global user.email "alexander@inperium.com" && git config --global user.name "inperiumcorp"

      - name: Maven settings.xml action
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/inperium-corp/${{ env.REPO_NAME }}", "snapshots.enabled": "true"}]'
          servers: '[{ "id": "github", "username": "${{ secrets.USERNAME }}", "password": "${{ secrets.PASSWORD }}" }]'

      - name: Set new incremental version
        run: |
          mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit
          cat /home/runner/.m2/settings.xml

      - name: Build and run tests
        run: mvn clean package

      - name: Publish to GitHub Packages
        run: mvn deploy -DuniqueVersion=false -Dmaven.source.useDefaultManifestFile=true -Dmaven.source.includePom=true -Dmaven.install.skip=true -DdeplyAtEnd=true -DaltDeploymentRepository='github::default::https://maven.pkg.github.com/inperium-corp/${{ env.REPO_NAME }}' --settings /home/runner/.m2/settings.xml
